# Summary:
# This workflow is named "Java CI Building with Maven" and is responsible for building a Java application using Maven.
#
# Trigger Events:
# - It is triggered on pull requests to the 'main' branch.
#
# Jobs:
# - The job "Build Java Application" runs on an Ubuntu machine and performs the following steps:
#   1. Checkout code: Pulls the latest code from the repository.
#   2. Setup Oracle JDK: Installs Oracle JDK 21.0.1.
#   3. Set Application Properties: Configures environment variables from secret properties for the Spring Boot application.
#   4. Build Spring Boot Application: Builds the Spring Boot application using Maven.

name: Java CI Building with Maven

on:
  pull_request:
    branches: [main] # Trigger workflow on pull request to main branch
  workflow_dispatch:

  # workflow_dispatch:

jobs:
  build:
    name: Build Java Application
    runs-on: ubuntu-latest # Use the latest Ubuntu runner for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Check out the repository code

      - name: Set up Oracle JDK 21.0.1
        uses: oracle-actions/setup-java@v1 # Set up Oracle JDK 21.0.1
        with:
          website: oracle.com
          release: 21
          version: 21.0.1
          
      - name: Ensure resources directory exists
        run: mkdir -p src/main/resources

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Building Spring Boot Application
        run: mvn clean install --file pom.xml
