# Summary:
# This workflow is named "Java CI Building with Maven" and is responsible for building a Java application using Maven.
#
# Trigger Events:
# - It is triggered on pull requests to the 'main' branch.
#
# Jobs:
# - The job "Build Java Application" runs on an Ubuntu machine and performs the following steps:
#   1. Checkout code: Pulls the latest code from the repository.
#   2. Setup Oracle JDK: Installs Oracle JDK 21.0.1.
#   3. Set Application Properties: Configures environment variables from secret properties for the Spring Boot application.
#   4. Build Spring Boot Application: Builds the Spring Boot application using Maven.

name: Java CI Building with Maven

on:
  pull_request:
    branches: [main] # Trigger workflow on pull request to main branch
  workflow_dispatch:

jobs:
  build:
    name: Build Java Application
    runs-on: ubuntu-latest # Use the latest Ubuntu runner for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Check out the repository code

      - name: Set up Oracle JDK 21.0.1
        uses: oracle-actions/setup-java@v1 # Set up Oracle JDK 21.0.1
        with:
          website: oracle.com
          release: 21
          version: 21.0.1

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Building Spring Boot Application
        env:
          SPRING_APPLICATION_NAME: ${{ vars.SPRING_APPLICATION_NAME }} # env variable
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }} # env secret
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }} # env secret
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }} # env secret
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${{ vars.SPRING_DATASOURCE_DRIVER_CLASS_NAME }} # env variable
          SPRING_JPA_HIBERNATE_DDL_AUTO: ${{ vars.SPRING_JPA_HIBERNATE_DDL_AUTO }} # env variable
          SPRING_JPA_SHOW_SQL: ${{ vars.SPRING_JPA_SHOW_SQL }} # env variable
          LOGGING_LEVEL_COM_CLOUDCOMPUTING_MOVIERETRIEVALWEBAPP_PACKAGE: ${{ vars.LOGGING_LEVEL_COM_CLOUDCOMPUTING_MOVIERETRIEVALWEBAPP_PACKAGE }} # env variable
          LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: ${{ vars.LOGGING_LEVEL_ORG_SPRINGFRAMEWORK }} # env variable
          LOGGING_LEVEL_ORG_HIBERNATE: ${{ vars.LOGGING_LEVEL_ORG_HIBERNATE }} # env variable
          LOGGING_LEVEL_COM_ZAXXER_HIKARI: ${{ vars.LOGGING_LEVEL_COM_ZAXXER_HIKARI }} # env variable
          LOGGING_LEVEL_ROOT: ${{ vars.LOGGING_LEVEL_ROOT }} # env variable
          LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_DEVTOOLS: ${{ vars.LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_DEVTOOLS }} # env variable

        run: mvn clean install --file pom.xml
