# Summary:
# This workflow is named "Packer Checks" and is responsible for performing validation and formatting checks on Packer templates.
#
# Trigger Events:
# - It is triggered on pull requests to the 'main' branch.
# - It can also be manually triggered via workflow dispatch.
#
# Jobs:
# - The job "Packer Check" runs on an Ubuntu machine and performs the following steps:
#   1. Checkout: Checks out the code from the repository.
#   2. Setup Packer: Installs the specified version of Packer (1.11.2).
#   3. Run `packer init`: Initializes the Packer environment with the specified template.
#   4. Run `packer fmt`: Formats the Packer template to ensure consistency.
#   5. Run `packer validate`: Validates the Packer template for any syntax or configuration issues.

name: Packer Checks

on:
  pull_request:
    branches: [main]

  # workflow_dispatch:

env:
  PRODUCT_VERSION: "1.11.2"

jobs:
  packer-check:
    name: Packer Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init cloudNativeAppAMI.pkr.hcl"

      - name: Run `packer fmt`
        id: fmt
        run: "packer fmt cloudNativeAppAMI.pkr.hcl"
