name: MySQL Action

on:
  pull_request:
    branches:
      [main]

jobs:
  mysql-job:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        options: >
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: test_db
          MYSQL_USER: aadityaKasbekar
          MYSQL_PASSWORD: REclassic@3504792

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for MySQL to start
        run: |
          sleep 30
          mysql --host 127.0.0.1 --port 3306 -u aadityaKasbekar -pREclassic@3504792 -e "SHOW DATABASES;"