name: Packer Checks

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  PRODUCT_VERSION: "1.11.2"

jobs:
  terraform-check:
    name: Packer Check.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init cloudNativeAppAMI.pkr.hcl"

      - name: Run `packer fmt`
        id: fmt
        run: "packer fmt cloudNativeAppAMI.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate cloudNativeAppAMI.pkr.hcl"
